name: KillCounter
version: '${version}'
main: it.feargames.killcounter.KillCounter

softdepend: [PlaceholderAPI]

commands:
  stats:
    description: Get your stats (kills, deaths and current kill streak)
    usage: /stats
    permission: killcounter.stats
